server:
  port: 9999

# Config Databases
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring
# Config Mail
  mail:
      host: smtp.gmail.com
      port: 587
      username: auth.zharver@gmail.com
      password: penguingame
      properties:
        mail:
          smtp:
            starttls:
              enabled: true
              required: true
            auth: true
            connectiontimeout: 5000
            timemout: 5000
            writetimeout: 5000
